name: tl19a08
description: Driver for the TL19A08 8-channel TTL output module.
dependencies:
  modbus:
    url: github.com/toitlang/pkg-modbus
    version: ^2.2.2
  rs485:
    url: github.com/toitware/toit-rs485
    version: ^1.2.0
